export enum TransactionCategory {
  SALARY = "SALARY",
  INVESTMENTS = "INVESTMENTS",
  FOOD = "FOOD",
  TRANSPORT = "TRANSPORT",
  HOUSING = "HOUSING",
  ENTERTAINMENT = "ENTERTAINMENT",
  TRAVEL = "TRAVEL",
  HEALTH = "HEALTH",
  SHOPPING = "SHOPPING",
  MISCELLANEOUS = "MISCELLANEOUS",
}
